# Generated by Django 3.1.3 on 2020-12-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='image_url',
            field=models.CharField(max_length=200),
        ),
    ]
