# Generated by Django 3.1.3 on 2020-12-06 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monsters', '0002_auto_20201206_1217'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teammembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teammembership_monster', to='monsters.monster')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teammembership_user', to='users.user')),
            ],
        ),
    ]
