# Generated by Django 3.1.3 on 2020-12-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_auto_20201204_0527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='difficulty',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='permalink',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='thumbnail_image',
            field=models.ImageField(blank=True, null=True, upload_to='tutorial/images'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='video_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
