# Generated by Django 3.1.3 on 2020-11-29 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20201129_0648'),
        ('orders', '0002_auto_20201129_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='id',
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_color',
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_current_price',
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_original_price',
        ),
        migrations.AddField(
            model_name='item',
            name='item',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='products.product'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_count',
            field=models.IntegerField(default=0),
        ),
    ]
