# Generated by Django 3.1.3 on 2020-11-29 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20201129_1105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_count',
            new_name='count',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='user_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='user_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='user_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='item',
        ),
        migrations.AddField(
            model_name='item',
            name='color',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
